import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import UserList from './UserList'
import Link from 'next/link';
import { Button } from '@mui/material';
import { color } from '@mui/system';

export default function Home() {
  const [usersList, setUsersList] = useState([])

  async function UserListFn() {
    const fetchUserData= await fetch("https://jsonplaceholder.typicode.com/users") 
    const userData= await fetchUserData.json()
    setUsersList(userData)
  }
  // UserListFn();

  useEffect(() => {
    UserListFn();
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
          <h3>LitNote-Next App</h3>
          <div className='UserListComponent'>
            <div className='align-right'>
              <Button variant="contained" color="success" size="medium"
                sx={{p:1,mr:1}}
                >Add User
              </Button>
            </div>
            <UserList usersList={usersList} />
          </div>
      </main>
    </>
  )
}
